/** Declaration file generated by dts-gen */

declare const pact_lang_api: {
    api: {
        mkPublicSend: any;
        mkSingleCmd: any;
        prepareExecCmd: any;
    };
    crypto: {
        base64UrlEncode: any;
        binToHex: any;
        genKeyPair: any;
        hash: any;
        hexToBin: any;
        sign: any;
        toTweetNaclSecretKey: any;
    };
    fetch: {
        listen: any;
        local: any;
        poll: any;
        send: any;
    };
    lang: {
        mkCap: any;
        mkExp: any;
        mkMeta: any;
    };
    simple: {
        exec: {
            createCommand: any;
            createListenRequest: any;
            createLocalCommand: any;
            createPollRequest: any;
        };
    };
    wallet: {
        sendSigned: any;
        sign: any;
    };
};

